config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  resources :session, only: [:create], path: '/user/session' do
    collection do
      get 'login'
      get 'logout'
    end
  end  
  resources :user, only: [:new,:create] do
    collection do
      get 'upload_question'
      post 'post_question'
      get  'upload_answer'
      post 'post_answer'
    end
  end

end

app/models/answer.rb
class Answer

  include Mongoid::Document
  include Mongoid::Timestamps
  field :ans, type: String

  validates :ans, presence: true
  validates :ans, uniqueness: true
  
  embedded_in :question
end

app/models/question.rb
class Question
	
  include Mongoid::Document
  include Mongoid::Timestamps
  field :question, type: String
  field :tag, type: String

  validates :question, presence: true
  validates :question, uniqueness: true

  belongs_to :user, :foreign_key => 'user_id'
  embeds_many :answers
  accepts_nested_attributes_for :answers

  # def self.tag
    
  # end
end

app/models/user.rb
class User
	include ActiveModel::SecurePassword
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :email, type: String
  field :user_name, type: String
  field :password_digest, type: String

  validates :name, :user_name, :email, :password_digest, presence: true
  validates :user_name, :email, uniqueness: true
  has_secure_password

  has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_logged_in?
  
  private
  
  def sign_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user = nil
    unless session[:user_id].nil?
      @current_user = User.find_by(id: session[:user_id]['$oid'])
    end
  end

  def user_logged_in?
    true if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def index
		@questions = Question.paginate(:page => params[:page], :per_page => 10)
	end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	def login
	end

	def create
		@user = User.find_by(email: params[:email])
		if @user
			  if @user.authenticate(params[:password])
			  	sign_in @user
		      redirect_to root_path
		      flash[:notice] = "Login successfully."
        else
        	redirect_to login_session_index_path, notice: "You have entered wrong password. Please try again"
        end	
		else
			redirect_to login_session_index_path, notice: "You have entered wrong email. Please try again!"
		end    
	end	

	def logout
		session[:user_id] = nil
		redirect_to root_path, notice: "Logged out successfully."
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :authenticate_user, :except => [:upload_answer,:new,:create]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
  	if @user.save
  		redirect_to root_path
  		flash[:success] = "New User Profile Created"
  	else
  		redirect_to new_user_path
  		flash[:notice] = @user.errors.full_messages.first		
  	end
	end


	def upload_question
		@question = Question.new
	end

	def post_question
		@ques = current_user.questions.build(question_params)
		if @ques.save
			redirect_to root_path
  		flash[:success] = "Question Uploaded Successfully"
  	else
  		redirect_to root_path
  		flash[:notice] = @ques.errors.full_messages.first 		
  	end		
	end

	def upload_answer
		@question = Question.find(params[:id])
		@answers = @question.answers || []
		@answer = Answer.new
	end

	def post_answer
		@ques = Question.find(params[:question_id])
		@answer = @ques.answers.build(answer_params)
		if @answer.save
			redirect_to root_path
  		flash[:success] = "Answer Uploaded Successfully"
  	else
  		redirect_to root_path
  		flash[:notice] = @answer.errors.full_messages.first		
  	end	
	end

	# def tags
	# 	@tags =  
	# end

	private

  def authenticate_user
  	unless current_user
  		redirect_to login_session_index_path, notice: "Please login to continue."
  	end
  end	

	def question_params
		params.require(:question).permit(:question, :tag)
	end

	def answer_params
		params.require(:answer).permit(:ans)
	end

	def user_params
		params.require(:user).permit(:name, :user_name, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
	def user_name question
		User.find(question.user_id).user_name 
	end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/dashboard/index.html.erb
<table class="ui fixed single line celled table">
  <thead>
    <tr>
      <th>Question</th>
      <th>tag</th>
      <th>User</th>
    </tr>
  </thead>
  
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td> <%= link_to question.question, upload_answer_user_index_path(id: question.id), target: "_blank" %> </td>
        <td><%= question.tag %></td>
        <td><%= user_name(question) %></td>
      </tr>
    <%end%>
    
  </tbody>
</table>
<%= will_paginate @questions %>

app/views/layouts/_header.html.erb
<div class="ui secondary  menu">
  
  <%= link_to "Questions", root_path, class: "item" %>
  <%= link_to "Tags", root_path, class: "item" %>
  
  <div class="right menu">
   
    <% if user_logged_in?  %>
      <%= link_to "Upload Question", upload_question_user_index_path, class: "item" %>
          
      <%= link_to "Logout", logout_session_index_path, class: "ui item active" %>
      
    <% else %>

      <%= link_to "SignUp", new_user_path, class: "ui primary button" %>
      <%= link_to "Login", login_session_index_path, class: "ui item active" %>
    
    <% end %> 
  </div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<%= semantic_flash %>
	<%= yield %>

</body>
</html>

app/views/session/login.html.erb
<div class="ui one column center aligned grid">
  <div class="column six wide form-holder">
    <h2 class="center aligned header form-head">Sign in</h2>
    <%= form_tag(session_index_path, method: :post, class: "ui form") do %>  
      <div class="field">
        <%= text_field_tag "email", nil, :placeholder => 'Email', :id => "login_email" %> 
      </div>
      <div class="field">
        <%= password_field_tag "password", nil, :placeholder => 'Password', :id => "login_password" %> 
      </div>
      <%= submit_tag "sign in", class: "ui button large fluid green", :id => "login_submit" %>
    <% end %>
  </div> 
</div>

app/views/user/new.html.erb
 <h2><center>User Registeration</center></h2>
<div class="ui segment">
<div class="ui middle aligned center aligned grid"> 

    <%= form_for @user, url: user_index_path, method: :post, html: {class: "ui large form"} do |f| %> 
      
      
         <%= f.text_field :name, class: 'field', placeholder: 'Name' %>
         <%= f.text_field :user_name, class: 'field', placeholder: 'User Name(unique)' %>     
         <%= f.email_field :email, class: 'field', placeholder: 'Email(unique)' %>
         <%= f.password_field :password,  class: 'field', placeholder: 'Password' %>
       
      
          
        <div class="ui message">
          <%= f.submit "Sign up", class: "ui fluid large teal submit button" %>
        </div>   
    <% end %>
  
</div>
</div>

app/views/user/upload_answer.html.erb
<div class="ui segment">
  <div class="ui equal width center aligned padded grid">
    <div class="row">
      <table class="ui selectable celled table">
        <thead>
          <tr class="ui inverted cell">
            <th>Question:- <%= @question.question %></th>
          </tr>
        </thead>

        <tbody>
        	<tr>
        		<td class="single line"> Answers:- </td>
        	</tr>
          <% @answers.each do |answer| %>
            <tr>
              
              <td class="single line"> <%= answer.ans %> </td>
            </tr>
          <% end %>  
        </tbody>

      </table>
    </div>
  </div>
</div>  


	  
<%= form_for @answer, url: post_answer_user_index_path, method: :post, html: {class: "ui form"} do |f| %>
 	<%= hidden_field_tag 'question_id', @question.id %>
	 	<div class="ui segment">
	 	  <label>Answer</label>
 			<%= f.text_area :ans, class: "field" %>
				<% if user_logged_in?  %>
				<%= f.submit :post, class: "ui button"%>
			<% else %>
				<%= link_to "Login To Post", login_session_index_path, class: "ui button" %>		 		
				<% end%>
 		</div>
<% end %>

app/views/user/upload_question.html.erb
<%= form_for @question, url: post_question_user_index_path, method: :post, html: {class: "ui form"} do |f| %> 

  <label>Question</label>
  <%= f.text_area :question, class: "field" %>
  <%= f.select("tag",["other","ruby", "rails", "java","c++","c"], {}) %>
  <%= f.submit :Post, class: "ui button"%>


<% end %>